# Generated by Django 5.1.14 on 2025-12-04 13:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Poll question", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Additional details"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this poll currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closes_at",
                    models.DateTimeField(
                        blank=True, help_text="When voting closes", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PollChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(help_text="Choice option text", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional details about this choice"
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="club.poll",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                (
                    "bike_photo_1",
                    models.ImageField(
                        blank=True,
                        help_text="First bike photo",
                        null=True,
                        upload_to="bikes/",
                    ),
                ),
                (
                    "bike_photo_2",
                    models.ImageField(
                        blank=True,
                        help_text="Second bike photo",
                        null=True,
                        upload_to="bikes/",
                    ),
                ),
                (
                    "bike_photo_3",
                    models.ImageField(
                        blank=True,
                        help_text="Third bike photo",
                        null=True,
                        upload_to="bikes/",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Short bio or description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Ride title", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the ride"),
                ),
                ("date_time", models.DateTimeField(help_text="When the ride starts")),
                (
                    "header_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Header image for the ride",
                        null=True,
                        upload_to="ride_headers/",
                    ),
                ),
                (
                    "calimoto_url",
                    models.URLField(
                        blank=True, help_text="Calimoto route URL", max_length=500
                    ),
                ),
                (
                    "relive_url",
                    models.URLField(
                        blank=True, help_text="Relive video URL", max_length=500
                    ),
                ),
                (
                    "start_point",
                    models.CharField(help_text="Starting location", max_length=300),
                ),
                (
                    "end_point",
                    models.CharField(help_text="Ending location", max_length=300),
                ),
                (
                    "gpx_file",
                    models.FileField(
                        blank=True,
                        help_text="GPX route file",
                        null=True,
                        upload_to="gpx_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["gpx"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Member who created this ride",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "riders",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Members participating in this ride",
                        related_name="rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_time"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="club.pollchoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-voted_at"],
                "unique_together": {("user", "choice")},
            },
        ),
    ]
