# Generated by Django 5.1.14 on 2025-12-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="completed",
            field=models.BooleanField(
                default=False, help_text="Mark as completed after ride is done"
            ),
        ),
    ]
