# Generated by Django 5.1.14 on 2025-12-06 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_ridephoto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RideComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(help_text="Comment text")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ride",
                    models.ForeignKey(
                        help_text="Associated ride",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="club.ride",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who posted the comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
