# Generated by Django 5.1.14 on 2025-12-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0004_ridecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="what3words_url",
            field=models.URLField(
                blank=True, help_text="What3Words location URL", max_length=500
            ),
        ),
    ]
